### ISSUE TITLE
Python module install

### ISSUE THREAD

**Issue by edouardkleinhans** [dlandon/zoneminder#28]
Hello, 

I think we have an issue with python module install

If I run the pip command found in 40_firstrun.sh for installing hook, it failed

```
root@d1d7eb3bd7a3:/config/hook# pip install numpy opencv-python imutils configparser Shapely future
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/da/32/1b8f2bb5fb50e4db68543eb85ce37b9fa6660cd05b58bddfafafa7ed62da/numpy-1.17.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-OjXLgx/numpy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-OjXLgx/numpy/
You are using pip version 8.1.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Due to wrong python version.

We should install python3-pip and run pip3 install ... and add module pyzmutils and requests in order to have /usr/bin/detect_wrapper.sh working

**Comment by dlandon** [comment]
Fixed is latest release.

**Comment by edouardkleinhans** [comment]
Still an issue with  

```
sudo -u www-data /usr/bin/detect_wrapper.sh

Traceback (most recent call last):
  File "/usr/bin/detect.py", line 20, in <module>
    import zmes_hook_helpers.log as log
  File "/usr/bin/zmes_hook_helpers/log.py", line 4, in <module>
    import pyzmutils.logger as zmlog
ImportError: No module named 'pyzmutils'

```
you need to add pyzmutils and requests modules in order to detect_wrapper to work

**Comment by dlandon** [comment]
Fixed in latest release.
